import Head from "next/head";
import Fuszeile from "../components/Fuszeile";
import Navigation from "../components/Navigation";

export default function Layout({ children }) {
    return (
        <div className="min-h-screen flex flex-col">
            <Head>
                <title>Vereinsbuddy</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navigation />
            
            <main className="flex-grow">
                {children}
            </main>

            <footer>
                <Fuszeile />
            </footer>
        </div>
    );
}
